name: Python Unit Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Clean-up for operation was cancelled bug https://github.com/vmware/concord-bft/pull/994
        run: |
          sudo rm -rf /ust/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install dependencies on Linux
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Run Tests on Linux
        run: |
          python -m unittest discover -s ./test

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencires on Windows
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Run Tests on Windows
        run: |
          python -m unittest discover -s ./test
